swagger: "2.0"
info:
  version: "2024-06-16T22:00:35Z"
  title: "Product Service"
host: "7pq38x9t4f.execute-api.eu-north-1.amazonaws.com"
basePath: "/prod"
schemes:
  - "https"
paths:
  /:
    options:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
  /products:
    get:
      summary: "Get all products"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                productId:
                  type: "string"
                productName:
                  type: "string"
  /products/{productId}:
    get:
      summary: "Get a product by ID"
      parameters:
        - name: "productId"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful response"
          schema:
            type: "object"
            properties:
              productId:
                type: "string"
              productName:
                type: "string"
        404:
          description: "Product not found"
        500:
          description: "Internal server error"
